name: 'Wuchale Status Check'

on:
  pull_request:
    branches:
      - main

jobs:
  wuchale-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run wuchale status
        id: wuchale_status
        env:
          NO_COLOR: 1
        run: |
          echo "Running wuchale status..."
          wuchale_output=$(npx wuchale status 2>&1 | sed 's/\x1B\[[0-9;]*[JKmsu]//g')
          echo "WUCHALE_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$wuchale_output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment PR
        uses: mshick/add-pr-comment@v2
        with:
          message-id: 'wuchale-status'
          message: |
            ## 🔍 Wuchale Status Check

            ```
            ${{ env.WUCHALE_OUTPUT }}
            ```

            *Status generated by `npx wuchale status`*
          repo-token: '${{ github.token }}'
